allowBuilds:
  '@prisma/engines': false
  core-js: true
  esbuild: true
  msw: false
  prisma: false
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
  - prisma
  - '@prisma/engines'
  - msw
